#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define SPLASH_STATE_SHOW_TIME 0.8

#define TITLE "Game Engine Starter - HCC"
#define SPLASH_SCENE_BACKGROUND_FILEPATH "Resources/Textures/splash_background.jpg"
#define MAIN_MENU_BACKGROUND_FILEPATH "Resources/Textures/main_menu_background.jpg"
#define MAIN_MENU_TITLE_FILEPATH "Resources/Textures/game_title.png"
#define MAIN_MENU_PLAY_BUTTON "Resources/Textures/play_button.jpg"

#define Card_Back "Resources/Textures/basicCards/back_card.png"

#define Card_H1 "1H_card.png"
#define Card_H2 "2H_card.png"
#define Card_H3 "3H_card.png"
#define Card_H4 "4H_card.png"
#define Card_H5 "5H_card.png"
#define Card_H6 "6H_card.png"
#define Card_H7 "7H_card.png"
#define Card_H8 "8H_card.png"
#define Card_H9 "9H_card.png"
#define Card_H10 "10H_card.png"
#define Card_H11 "11H_card.png"
#define Card_H12 "12H_card.png"
#define Card_H13 "13H_card.png"
#define Card_D1 "1D_card.png"
#define Card_D2 "2D_card.png"
#define Card_D3 "3D_card.png"
#define Card_D4 "4D_card.png"
#define Card_D5 "5D_card.png"
#define Card_D6 "6D_card.png"
#define Card_D7 "7D_card.png"
#define Card_D8 "8D_card.png"
#define Card_D9 "9D_card.png"
#define Card_D10 "10D_card.png"
#define Card_D11 "11D_card.png"
#define Card_D12 "12D_card.png"
#define Card_D13 "13D_card.png"
#define Card_S1 "1S_card.png"
#define Card_S2 "2S_card.png"
#define Card_S3 "3S_card.png"
#define Card_S4 "4S_card.png"
#define Card_S5 "5S_card.png"
#define Card_S6 "6S_card.png"
#define Card_S7 "7S_card.png"
#define Card_S8 "8S_card.png"
#define Card_S9 "9S_card.png"
#define Card_S10 "10S_card.png"
#define Card_S11 "11S_card.png"
#define Card_S12 "12S_card.png"
#define Card_S13 "13S_card.png"
#define Card_C1 "1C_card.png"
#define Card_C2 "2C_card.png"
#define Card_C3 "3C_card.png"
#define Card_C4 "4C_card.png"
#define Card_C5 "5C_card.png"
#define Card_C6 "6C_card.png"
#define Card_C7 "7C_card.png"
#define Card_C8 "8C_card.png"
#define Card_C9 "9C_card.png"
#define Card_C10 "10C_card.png"
#define Card_C11 "11C_card.png"
#define Card_C12 "12C_card.png"
#define Card_C13 "13C_card.png"